sudo: required
services:
    - docker

before_install:
    - docker build -t yan8909/react-test -f ./client/Dockerfile.dev ./client

script:
    - ddocker run -e CI=true yan8909/react-test npm test

after_success:
    - docker build -t yan8909/multi-client ./client
    - docker build -t yan8909/multi-nginx ./nginx
    - docker build -t yan8909/multi-server ./server
    - docker build -t yan8909/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push yan8909/multi-client
    - docker push yan8909/multi-nginx
    - docker push yan8909/multi-server
    - docker push yan8909/multi-worker